### ISSUE TITLE
Uninstall fails and doesn't attempt to totally clean up

### ISSUE THREAD

**Issue by dleve123** [scmbreeze/scm_breeze#205]
The uninstall script seems to be broken on MBP (10.11.4): 

``` bash
dan@kraken:~
$ ~/.scm_breeze/uninstall.sh
sed: 1: "/Users/dan/.bashrc": extra characters at the end of d command
== Removed SCM Breeze from '/Users/dan/.bashrc'
sed: 1: "/Users/dan/.zshrc": extra characters at the end of d command
== Removed SCM Breeze from '/Users/dan/.zshrc'
```

Moreover, running the uninstall script doesn't attempt to remove the scm_breeze configuration files placed within `~` on installation:

``` bash
dan@kraken:~
$ ls -al | grep scm
-rw-r--r--    1 dan   staff   4064 May 21 14:59 .git.scmbrc
drwxr-xr-x   14 dan   staff    476 May 21 14:58 .scm_breeze
-rw-r--r--    1 dan   staff    607 May 21 14:59 .scmbrc
```

**Comment by hammady** [comment]
Just came across this issue through a google search.
The `search -i` on Mac differs from the Linux counterpart as it requires a mandatory parameter (backup extension), this is what you need to do in `.scm_breeze/uninstall.sh`:
instead of:
`sed -i '/scm_breeze/d' "$HOME/.$rc"`
do:
`sed -i '' '/scm_breeze/d' "$HOME/.$rc"`

Someone needs to send a pull request for this.
Sorry I'm just a passer-by :)

**Comment by ghthor** [comment]
Oh good, I'll get too this soon! Thanks! =)
