### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by omnikron** [scmbreeze/scm_breeze#237]
@ndbroadbent just saw your request for maintainers – I would be more than happy to help out, I've been using scm_breeze every day for years and it is an integral part of my workflow. I'm more of a rubyist than a bash scripter but let me know if there's anything you would like to try delegating.

**Comment by ndbroadbent** [comment]
Thanks @omnikron! I actually haven't worked on this for a very long time, although I'm still using it every day. @ghthor has been helping out and doing a great job. So I'm not sure if there's anything specific that needs to be done, but you're more than welcome to help reviewing some pull requests or looking at issues!

**Comment by omnikron** [comment]
Alright, sweet! I will take a look (after the weekend :bowtie: ).  Thanks for making this, it is the best thing. Have a good one!

**Comment by ghthor** [comment]
@omnikron Hey! Thanks for your interest. The main focus from support has been to cut out some of the unused features and do what we can to simplify the codebase remaining.

**Comment by omnikron** [comment]
@ghthor hello! OK cool – I had a look through the issues and PRs but realised that I'm really not very conversant with bash scripting, so I may not be very useful, but I can have a go! When you say unused features – how do we know what is used and what isn't?

**Comment by ghthor** [comment]
@omnikron Here's some things you could do =)

1. https://github.com/scmbreeze/scm_breeze/issues/220 This was the main idea about pruning the functionality. This feature isn't widely used and would be better if it was provided as a separate project.

2. We did a pretty good job of triage'ing the open issues/PRs list a few months ago, but this is something that could always use another pair of eyes. If you'd like to take a pass over any of the open issues or PR's and chime in on if the bug was reproducible or if the PR is relevant anymore.

3. You mentioned you're a rubyist. There are some ruby scripts that you could look over and perhaps make some improvements to.

**Comment by omnikron** [comment]
Thanks @ghthor! I'll take a look.

**Comment by jeffbyrnes** [comment]
I’m also a longtime user, and have been trying to help where I can. My bash-fu is pretty decent, I’m pretty strong with Ruby, and I’ve chimed in on #220 previously.
