### ISSUE TITLE
Git status output hangs after "changes to be committed"

### ISSUE THREAD

**Issue by tekumara** [scmbreeze/scm_breeze#241]
On both zsh and bash I get:

```
$ gs
 # On branch:   |  [*] => $e*
 #
 ➤ Changes to be committed
 #
```
And the output just hangs.

It's something specific to a repo, because other repos work fine.

**Comment by omnikron** [comment]
What is the output of `git status` – any weirdness?

**Comment by tukushan** [comment]
`git status` had nothing out of the ordinary, 2 changes not staged for commit, 2 untracked files.

I'm since made some additional commits, and now the problem has gone away.

**Comment by tukushan** [comment]
Now it's back. It appears to occur with there is a change to a large file. In my case I made a single character addition to a 2.5MB CSV, which caused `gs` to freeze but `git status` works fine.

**Comment by ghthor** [comment]
Interesting, I'll try to reproduce in the morning. Thanks for this bug
report!

**Comment by ghthor** [comment]
I repro this in a repo with lots of submodules. @tukushan was your repo using submodules at all?

**Comment by tukushan** [comment]
No submodules for me.

**Comment by ghthor** [comment]
I've seen this again in a repo without any submodules. Unable to nail this down.

**Comment by EdvinOlofsson** [comment]
Was this issue ever found? I'm having the same issue.

I can reproduce this with a clean git repo. For me it happens if I 'git mv' a file from one folder to another.
psuedo example:

./repo/folder1/file1.txt
./repo/folder2/file2.txt
cd repo
git mv folder1/file1.txt folder2/
gs <-- hangs exactly like shown above.

I'm on Ubuntu 18.04.2
