### ISSUE TITLE
Broken `scmb_wrapped_shell_commands` in ZSH

### ISSUE THREAD

**Issue by p-himik** [scmbreeze/scm_breeze#284]
Commit a6eeebfa91e51ec7aae21f65e0df49e461a4ca68 breaks `scmb_wrapped_shell_commands` in ZSH. It makes the loop make only one iteration with `cmd` being equal to `scmb_wrapped_shell_commands`.
The workaround is to write `scmb_wrapped_shell_commands` in the config not as a string but as an array.

**Comment by ghthor** [comment]
I assume that's the workaround you're using personally from you zsh configuration? There's got to be a way to fix the internal code that's functional for zsh+bash. I'm sorry about your zsh issues, I've been meaning to run zsh personally and just haven't made the push yet.

**Comment by p-himik** [comment]
Indeed, I just changed my local configuration, only not of zsh but of scm_breeze in `.git.scmbrc`.

**Comment by ghthor** [comment]
Right, You've change the declaration in `.git.scmbrs` from a space
separated string into a array literal?

I think we can't support that official because array literals are a recent
bash feature? If I'm wrong about this, I blame bash, well I blame bash
anyway. At any rate there is a way to fix this at the usage site and lemme
see if I can hack it together and get it tested today.

**Comment by p-himik** [comment]
Yep, now it just looks something like `("vim" "rm" "mv")`. Sorry, I have no idea what versions of bash support this feature.

**Comment by HaleTom** [comment]
In #260 we established minimum shell versions:

```
bash: 4.3.11(1)
zsh: 5.0.2
```

Both of these support arrays.

There's a `zsh` gotcha mentioned in #260 also, which may or may not be relevant.

To enable proper quoting, arrays are sometimes required (see my largish PR for instance), eg if one argument token contains spaces for instance.

I see this as a documentation bug rather than a code bug.
